global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "score-app"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["score-app:8181"]  
        labels:
          service: "score-app"